[workspace]
resolver = "2"
members = [
    "aoc-runner",
    "aoc2015", 
    "aoc2024",
]
exclude = ["inputs"]


[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Bhuwan Pandit"]
description = "My solution to all the advent of code puzzles"
