[package]
name = "aoc-runner"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
aoc2015 = { path = "../aoc2015" }
aoc2024 = { path = "../aoc2024" }
